### ISSUE TITLE
Can we stop installing pip2

### ISSUE THREAD

**Issue by felddy** [cisagov/ansible-role-pip#6]
Why are we installing pip for python2?  (cyhy-core et al.?) 

https://github.com/cisagov/ansible-role-pip/blob/1afd216a6ea2e7547cb8e9dc43ef1790dbfbc1c5/tasks/main.yml#L9-L10

This is causing roles that use pip further down the line to install requested packages in the python2 path instead of the python3.   The work around is to explicitly tell ansible to use pip3.  

https://github.com/cisagov/ansible-role-openvpn/blob/1bcde32a86781f50ceb43c78b68a57a56d45c447/tasks/main.yml#L14-L18

I'd like to see this role only install pip3, and if someone needs pip2 we can make a separate role for that.  

For what it's worth I tried telling packer to use ansible with python3.  According to the docs for the pip module of ansible this should have then used pip3 by default.  This wasn't the case:

https://github.com/cisagov/openvpn-packer/commit/9674b82f66112f2534d805a09a56ea7c4022e72b

**Comment by jsf9k** [comment]
We still have code (cyhy-core, for example) that uses Python 2.

**Comment by felddy** [comment]
@jsf9k please comment about Debian 9.

**Comment by jsf9k** [comment]
All our other projects are moving forward with python3, but we still need to support python2 for the Cyber Hygiene AMIs.  (For now - Cyber hygiene will be moved to python3.)

As it turns out, Debian 9 is used for the Cyber Hygiene AMIs and _only_ for the Cyber Hygiene AMIs.  In addition, Ansible will use `/usr/bin/python` if it exists but will find and use `/usr/bin/python3*` for most distributions if `/usr/bin/python` does not exist.

Therefore we can handle both cases by:
* Installing both python2 and pip2 _and_ python3 and pip3 on Debian 9.
* Installing _only_ python3 and pip3 everywhere.
* Making sure that any roles or tasks that force the installation of python2 on non-Debian 9 platforms are run at the end of the playbook.

I made the change described in the first two bullets in [cisagov/ansible-role-pip](https://github.com/cisagov/ansible-role-pip) and [cisagov/ansible-role-python](https://github.com/cisagov/ansible-role-python), and I am making the changes described in the last bullet as i rebuild non-CyHy AMIs.  (See, for example, cisagov/kali-packer#22.)
